planeVersion: latest

dockerhub:
  enabled: false
  loginid: makeplane
  password: makeplane
  images:
    frontend: makeplane/plane-frontend
    space: makeplane/plane-space
    backend: makeplane/plane-backend

ingress:
  enabled: true
  appHost: 'plane.example.com'
  minioHost: 'plane-minio.example.com'
  ingressClass: 'nginx'
  clientMaxBodySize: 10m
ssl:
  enable: true
  createIssuer: false
  issuer: "http" # Allowed : cloudflare, digitalocean, http
  token: "" # not required for http

  # STAGING
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  # PRODUCTION
  # server: https://acme-v02.api.letsencrypt.org/directory 
  email: plane@example.com
  generateCerts: false

redis:
  local_setup: true
  image: redis:6.2.7-alpine
  servicePort: 6379
  storageClass: local-path
  volumeSize: 1Gi

postgres:
  local_setup: true
  image: postgres:15.2-alpine
  servicePort: 5432
  cliConnectPort: 30000
  storageClass: local-path
  volumeSize: 5Gi

minio:
  local_setup: true
  image: minio/minio:RELEASE.2023-10-25T06-33-25Z
  storageClass: local-path
  volumeSize: 5Gi
  root_user: admin
  root_password: password

web:
  replicas: 3
  memoryLimit: 300Mi
  cpuLimit: 200m
  hscale:
    minReplicas: 2
    maxReplicas: 15
    precentMemoryUtilization: 80
    percentCpuUtilization: 60

space:
  replicas: 3
  memoryLimit: 300Mi
  cpuLimit: 200m
  hscale:
    minReplicas: 2
    maxReplicas: 10
    precentMemoryUtilization: 80
    percentCpuUtilization: 60

api:
  replicas: 3
  memoryLimit: 300Mi
  cpuLimit: 200m

worker:
  replicas: 1
  memoryLimit: 300Mi
  cpuLimit: 200m

beatworker:
  replicas: 1
  memoryLimit: 300Mi
  cpuLimit: 200m

smtp:
  host: 
  user: ""
  password:  ""
  port: 587
  from:  "Plane Mailer <team@mailer.example.com>"
  use_tls: 1
  use_ssl: 0

openai:
  api_base: "https://api.openai.com/v1"
  api_key: "" #looks like => sk-xxxxxxx
  model: "gpt-3.5-turbo"


oauth:
  enabled: 0
  google_client_id: ""
  github_client_id: ""
  github_client_secret: ""

cert-manager:
  enabled: false
  installCRDs: true
  startupapicheck:
    enabled: false

env:
  pgdb_username: plane
  pgdb_password: plane
  pgdb_name: plane
  pgdb_remote_url: "" #INCASE OF REMOTE PG DB URL ONLY

  # NEXT_PUBLIC_DEPLOY_URL:  ""
  # REDIS
  remote_redis_url: "" #INCASE OF REMOTE REDIS ONLY
  # POSTGRES DB VALUES

  # DATA STORE
  docstore_bucket: "uploads"
  doc_upload_size_limit: "5242880" # 5MB

  # REQUIRED IF MINIO LOCAL SETUP IS FALSE
  aws_access_key: ""
  aws_secret_access_key: ""
  aws_region: ""
  
  # # LOGIN/SIGNUP SETTINGS
  enable_signup: 1
  enable_email_password: 1
  enable_magic_link_login: 0
  secret_key: "60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5"

  sentry_dsn: ""
  sentry_environment: ""

  gunicorn_api_workers: 1
  admin_email: "admin@example.com"
  license_engine_base_url: "https://control-center.plane.so"
  
