{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.clientMaxBodySize | default "5m" | quote}}
    {{- if .Values.ssl.generateCerts }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer | default "letsencrypt" | quote}}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
    - host: {{ .Values.ingress.appHost }}
      http:
        paths:
          - backend:
              service:
                port:
                  number: 3000
                name: {{ .Release.Name }}-web
            path: /
            pathType: Prefix
          - backend:
              service:
                port:
                  number: 8000
                name: {{ .Release.Name }}-api
            path: /api
            pathType: Prefix
          - backend:
              service:
                port:
                  number: 3000
                name: {{ .Release.Name }}-space
            path: /spaces
            pathType: Prefix
          {{- if .Values.minio.local_setup }}
          - backend:
              service:
                port:
                  number: 9000
                name: {{ .Release.Name }}-minio
            path: /{{ .Values.env.docstore_bucket }}
            pathType: Prefix
          {{- end }}

    {{- if and .Values.minio.local_setup .Values.ingress.minioHost }}
    - host: {{ .Values.ingress.minioHost }}
      http:
        paths:
          - backend:
              service:
                port:
                  number: 9090
                name: {{ .Release.Name }}-minio
            path: /
            pathType: Prefix
    {{- end }}
  tls:
    {{- if or .Values.ssl.generateCerts .Values.ssl.enable }}
    - hosts:
      - {{ .Values.ingress.appHost | quote }}
      {{ if .Values.ingress.minioHost }}
      - {{ .Values.ingress.minioHost | quote }}
      {{ end }}
       {{- if .Values.ssl.generateCerts }}
      secretName: {{ .Release.Name }}-ssl-cert
      {{ end }}
    {{- end }}
{{- end }}
